<?php
/**
 * @license Copyright 2016-2017 Smartex.io Ltd., MIT License
 * 
 */

/**
 * @see Smartex\Core\Block\Form\Smartex
 */
 
$_code = $block->getMethodCode();
$smartexScope = \Magento\Framework\App\ObjectManager::getInstance()->get('\Magento\Framework\App\Config\ScopeConfigInterface');
if ($smartexScope->getValue('payment/smartex/fullscreen')) {
	echo '<ul class="form-list" id="payment_form_' . $_code . '" style="display:none;">' .
	         '<li>You will be transfered to <a href="https://smartex.io" target="_blank">Smartex</a> to complete your purchase when using this payment method.</li>' .
	     '</ul>';
}
?>
